version: '3.8'

services:
  app:
    build: .
    container_name: university_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: university_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - university_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7.0
    container_name: university_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: university_mongo
    volumes:
      - university_mongo_data:/data/db

  mailhog:
    image: mailhog/mailhog:latest
    container_name: university_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  university_pgdata:
  university_mongo_data: